version: "3"

services:

  postgres:
    container_name: postgres-bot
    image: postgres:12-alpine
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_DB=${PG_NAME}
      - PGDATA=${PG_DATA}
    ports:
      - ${PG_PORT}:${PG_PORT}
    expose:
      - ${PG_PORT}
    volumes:
      - /usr/src/app/data:/var/lib/postgresql/data/pgdata

  bot:
    container_name: telegram-bot
    build: .
    restart: always
    env_file:
      - .env
    links:
      - postgres

    depends_on:
      - postgres


volumes:
  postgres-data:
